import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monsterrat.className}>
        <Theme>
          <NavBar />
          <main>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
